services:
  renode:
    image: electricdrivesystems/renode:local
    build:
      context: .
      dockerfile: Dockerfile
    container_name: renode
    tty: true
    stdin_open: true
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/home/developer/.Xauthority
      - NO_AT_BRIDGE=1
    volumes:
      - ${XAUTHORITY}:/home/developer/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./scripts:/scripts
